#Application Configuration
server:
  port: 8200
  error:
    include-message: always
    include-binding-errors: always

spring:
  mail:
    host: ${MAIL_HOSTNAME}
    port: ${MAIL_PORT}
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    properties.mail.smtp: auth:true
      starttls.enable:true
      connectiontimeout:5000
      timeout:5000
      writetimeout:5000

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"


sendo:
  api:
    url: ${SENDO_API_URL}
    key: ${SENDO_API_KEY}
  sender:
    id: ${SENDO_SENDER_ID}

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"
