#Application Configuration
server:
  port: 5010
  error:
    include-message: always
    include-binding-errors: always

spring:        
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?autoReconnect=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka
        
api:
  erp-sofya:
    base-url: ${ERP_SOFYA_URL}
    base-url-tv: ${ERP_SOFYA_URL_TV}
    phone-path: ${ERP_SOFYA_PHONE_PATH}
    token-path: ${ERP_SOFYA_TOKEN_PATH}
    biometric-path: ${ERP_SOFYA_BIOMETRIC_PATH}
    contract-state-path: ${ERP_SOFYA_CONTRACT_STATE_PATH}
    client-id: ${ERP_SOFYA_CLIENT_ID}
    client-secret: ${ERP_SOFYA_SECRET_ID}
    client-tv-id: ${ERP_SOFYA_CLIENT_TV_ID}
    client-tv-secret: ${ERP_SOFYA_SECRET_TV_ID}
    approve-contract: ${ERP_SOFYA_APPROVE}
    discard-contract: ${ERP_SOFYA_DISCARD}
    contract-state: ${ERP_SOFYA_STATE}


