#Application Configuration
server:
  port: 5003
  error:
    include-message: always
    include-binding-errors: always

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?autoReconnect=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  codec:
    max-in-memory-size: 16MB
  mvc:
    async:
      request-timeout: 120000
  webflux:
    session:
      timeout: 120s
    netty:
      idle-timeout: 120s

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

api:
  backoffice-firebase:
    url: lb://backoffice-firebase/backoffice/api/v1/messaging
  backoffice-journal:
    url: lb://backoffice-journal/backoffice/api/v1/journal
  backoffice-contacts:
    url: lb://backoffice-contacts/backoffice/api/v1/contacts
        
