#Application Configuration
server:
  port: 5010
  error:
    include-message: always
    include-binding-errors: always

spring:        
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}?autoReconnect=true
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MariaDBDialect

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka
        
api:
  erp-sofya:
    base-url: https://test-erp.credituphone.com:8091/com.sofya.java.uphone.backend.apiRest-1.1/uphoneAPI
    phone-path: /contratoAPI/updatePhone
    token-path: /auth/login
    client-id: f2a1ed52710d4533bde25be6da03b6e3
    client-secret: 9876543210zyxwvutsrqponmlkjihgfedcba

