#Application Configuration
server:
  port: 5050

spring:
  application:
    name: recognito-holder
  iaaa:
    base-url: http://localhost:5005
  security:
    client-app: holder
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none # o update, validate, create-drop según tu caso
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
    show-sql: false

  devtools:
    restart:
      enable: false


management:
  endpoints:
    web:
      exposure:
        include: health,info

metrics:
  validation-percent: ${VALIDATION_PERCENT}
  validation-ratio : ${VALIDATION_RATIO}


geocoding:
  timeout-seconds: 10
  service-url: "https://nominatim.openstreetmap.org"
  user-agent: "UphoneRecognitoHolder/1.0"

custome: 
  label: 
    projectVersionArn: ${PROJECT_VERSION_ARN}
    minCoincidencial: ${MIN_COINCIDENCIAL}
    tagValidation: ${TAG_VALIDATION}

#EurekaClient
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@${EUREKA_HOSTNAME}:${EUREKA_PORT}/eureka



api:
  erp-provider:
    base_url: ${ERP_PROVIDER_BASE_URL}
    face: ${ERP_PROVIDER_FACE_PATH}
    result: ${ERP_PROVIDER_RESULT_PATH}
    msg_result: ${MSG_RESULT}
    approve: ${ERP_PROVIDER_APPROVE}
    discard: ${ERP_PROVIDER_DISCARD}
  uphone-erp:
    url: lb://backoffice-erp/backoffice/api/v2/erp


modeldecision:
  url: ${MODELDECISION_URL}
  tabledecision: ${MODELDECISION_TABLE}
  agency: ${MODELDECISION_AGENCY}
